name = "SallyScope"
uuid = "bdc509e6-e5f8-4c54-b183-09f7d375e776"
authors = ["Ted Dunning <ted.dunning@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1.10.0"
julia = "1.11"
